apiVersion: v1
kind: Service
metadata:
  name: takenote-service
spec:
  selector:
    app: takenote
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort  # You can change it to ClusterIP or NodePort based on your needs
